=== MarkSeliverstov/NPRG036-data-formats/HW3/xml/schemas/schema-2.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:ex="http://example.org/vocabulary/"
           xmlns:xml="http://www.w3.org/XML/1998/namespace"
           targetNamespace="http://example.org/vocabulary/"
           elementFormDefault="qualified">

    <!-- Import XML namespace -->
    <xs:import namespace="http://www.w3.org/XML/1998/namespace" 
              schemaLocation="https://www.w3.org/2001/03/xml.xsd"/>

    <!-- Define a complex type for elements that need xml:lang -->
    <xs:complexType name="localizedString">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="xml:lang" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- Student Type -->
    <xs:complexType name="StudentType">
        <xs:sequence>
            <xs:element name="name" type="ex:localizedString"/>
            <xs:element name="email" type="ex:EmailType"/>
            <xs:element name="phone" type="ex:PhoneType" maxOccurs="unbounded"/>
            <xs:element name="programEnrollment" type="ex:ProgramEnrollmentType"/>
            <xs:element name="courseEnrollments" type="ex:CourseEnrollmentsListType"/>
        </xs:sequence>
        <xs:attribute name="id" type="ex:StudentIDType" use="required"/>
    </xs:complexType>

    <!-- Program Type -->
    <xs:complexType name="ProgramType">
        <xs:sequence>
            <xs:element name="name" type="ex:localizedString"/>
            <xs:element name="duration" type="ex:ProgramDurationType"/>
        </xs:sequence>
        <xs:attribute name="id" type="ex:ProgramIDType" use="required"/>
    </xs:complexType>

    <!-- Program Enrollment Type -->
    <xs:complexType name="ProgramEnrollmentType">
        <xs:sequence>
            <xs:element name="program" type="ex:ProgramType"/>
        </xs:sequence>
        <xs:attribute name="year" type="ex:EnrollmentYearType" use="required"/>
    </xs:complexType>

    <!-- Course Enrollments List Type -->
    <xs:complexType name="CourseEnrollmentsListType">
        <xs:sequence>
            <xs:element name="enrollment" type="ex:EnrollmentType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Enrollment Type -->
    <xs:complexType name="EnrollmentType">
        <xs:sequence>
            <xs:element name="grade" type="ex:GradeType"/>
            <xs:element name="enrolledOn" type="xs:date"/>
            <xs:element name="completedOn" type="xs:date" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="ex:EnrollmentIDType" use="required"/>
        <xs:attribute name="courseRef" type="ex:CourseRefType" use="required"/>
        <xs:attribute name="semester" type="ex:SemesterType" use="required"/>
        <xs:attribute name="year" type="ex:EnrollmentYearType" use="required"/>
    </xs:complexType>

    <!-- Simple Types -->
    <xs:simpleType name="StudentIDType">
        <xs:restriction base="xs:ID">
            <xs:pattern value="s[0-9]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ProgramIDType">
        <xs:restriction base="xs:ID">
            <xs:pattern value="p[0-9]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="EnrollmentIDType">
        <xs:restriction base="xs:ID">
            <xs:pattern value="e[0-9]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CourseRefType">
        <xs:restriction base="xs:string">
            <xs:pattern value="c[0-9]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="EmailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^@]+@[^\.]+\..+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="PhoneType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\+[0-9]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="GradeType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="5"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ProgramDurationType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="6"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="SemesterType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Fall"/>
            <xs:enumeration value="Spring"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="EnrollmentYearType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="2000"/>
            <xs:maxInclusive value="2100"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Root Element -->
    <xs:element name="students">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" type="ex:StudentType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

        <!-- Keys -->
        <xs:key name="StudentKey">
            <xs:selector xpath="ex:student"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <xs:key name="ProgramKey">
            <xs:selector xpath=".//ex:program"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <xs:key name="EnrollmentKey">
            <xs:selector xpath=".//ex:enrollment"/>
            <xs:field xpath="@id"/>
        </xs:key>
    </xs:element>
</xs:schema>

=== MarkSeliverstov/NPRG036-data-formats/HW3/xml/data/data-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<ex:students xmlns:ex="http://example.org/vocabulary/"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://example.org/vocabulary/ ../schemas/schema-2.xsd">

      <ex:program id="p1">
            <ex:name xml:lang="en">Computer Science</ex:name>
            <ex:duration>4</ex:duration>
       </ex:program>

        <ex:program id="p2">
            <ex:name xml:lang="en">Data Science</ex:name>
            <ex:duration>2</ex:duration>
       </ex:program>

        <ex:program id="p3">
            <ex:name xml:lang="en">Mathematics</ex:name>
            <ex:duration>3</ex:duration>
        </ex:program>

    <!-- Student: Alice -->
    <ex:student id="s1" programRef="p1">
        <ex:name xml:lang="en">Alice</ex:name>
        <ex:email>student1@b.cz</ex:email>
        <ex:phone>+123456789</ex:phone>
        <ex:phone>+987654321</ex:phone>
        <ex:courseEnrollments>
            <ex:enrollment id="e1" courseRef="c1">
                <ex:grade>2</ex:grade>
                <ex:enrolledOn>2020-09-01</ex:enrolledOn>
                <ex:completedOn>2021-01-01</ex:completedOn>
            </ex:enrollment>
        </ex:courseEnrollments>
    </ex:student>

    <!-- Student: Bob -->
    <ex:student id="s2" programRef="p2">
        <ex:name xml:lang="en">Bob</ex:name>
        <ex:email>bob@b.cz</ex:email>
        <ex:courseEnrollments>
            <ex:enrollment id="e2" courseRef="c2">
                <ex:grade>1</ex:grade>
                <ex:enrolledOn>2020-09-01</ex:enrolledOn>
                <ex:completedOn>2021-01-01</ex:completedOn>
            </ex:enrollment>
        </ex:courseEnrollments>
    </ex:student>

    <!-- Student: Charlie -->
    <ex:student id="s3" programRef="p3">
        <ex:name xml:lang="en">Charlie</ex:name>
        <ex:email>Charlie@a.cz</ex:email>
        <ex:phone>+123456789</ex:phone>
        <ex:courseEnrollments>
            <ex:enrollment id="e3" courseRef="c3">
                <ex:grade>3</ex:grade>
                <ex:enrolledOn>2020-09-01</ex:enrolledOn>
                <ex:completedOn>2021-01-01</ex:completedOn>
            </ex:enrollment>
        </ex:courseEnrollments>
    </ex:student>
</ex:students>
